-- Habilitar extensión para generación de UUIDs si no está activa
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- 1. Tabla de Proyectos
CREATE TABLE IF NOT EXISTS proyectos (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    nombre TEXT UNIQUE NOT NULL,
    categoria TEXT,
    ubicacion TEXT,
    extension TEXT,
    fecha_inauguracion TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- 2. Tabla de Estadísticas de Seguridad
CREATE TABLE IF NOT EXISTS seguridad_estadisticas (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    proyecto_id UUID REFERENCES proyectos(id) ON DELETE CASCADE,
    anio TEXT NOT NULL,
    variable TEXT NOT NULL,
    valor NUMERIC,
    tipo TEXT DEFAULT 'observado', -- 'observado' o 'proyectado'
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- 3. Tabla de Registros de Economía (Aperturas y Renovaciones de Negocios)
CREATE TABLE IF NOT EXISTS economia_registros (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sector_raw TEXT,
    movimiento_raw TEXT,
    fecha_impresion DATE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- Crear índices para optimizar las consultas de cruce de economía
CREATE INDEX IF NOT EXISTS idx_economia_registros_sector ON economia_registros(sector_raw);
CREATE INDEX IF NOT EXISTS idx_economia_registros_fecha ON economia_registros(fecha_impresion);

-- 4. Tabla de Valor de Suelo
CREATE TABLE IF NOT EXISTS valor_suelo (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    proyecto TEXT NOT NULL,
    descripcion TEXT,
    valor_2022_2023 NUMERIC,
    valor_2024 NUMERIC,
    valor_2026 NUMERIC,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- Crear índice para búsquedas por proyecto en valor de suelo
CREATE INDEX IF NOT EXISTS idx_valor_suelo_proyecto ON valor_suelo(proyecto);

-- 5. Tabla de Fichas de Senderos (Metadatos institucionales)
CREATE TABLE IF NOT EXISTS senderos_fichas (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    proyecto_id UUID REFERENCES proyectos(id) ON DELETE CASCADE,
    anio INT NOT NULL,
    ejecutor TEXT,
    presupuesto TEXT,
    extension TEXT,
    beneficiarios TEXT,
    fecha TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);
